# Generated by Django 3.2.16 on 2022-11-14 13:44

from django.db import migrations, models
import useful_variables


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('insufficient', 'insufficient'), ('sufficient', 'sufficient'), ('good', 'good'), ('very good', 'very good'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=12)),
                ('type_of_activity', models.CharField(choices=[('Test paper', 'Test paper'), ('Listening', 'Listening')], max_length=12)),
                ('school_subject', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('Art', 'Art'), ('Geography', 'Geography'), ('History', 'History'), ('Music', 'Music'), ('Logic', 'Logic'), ('Chemistry', 'Chemistry'), ('Informatics', 'Informatics')], max_length=20)),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(default=None, max_length=40)),
                ('phone_number', models.CharField(max_length=10, validators=[useful_variables.phone])),
                ('address', models.CharField(default=None, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
