# Generated by Django 3.2.16 on 2022-11-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user_type',
        ),
    ]
