# Generated by Django 3.2.16 on 2022-11-14 13:44

from django.db import migrations, models
import useful_variables


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10, validators=[useful_variables.phone])),
                ('email', models.CharField(max_length=30)),
                ('parent_type', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather')], max_length=11)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
