# Generated by Django 3.2.16 on 2022-11-14 13:44

from django.db import migrations, models
import useful_variables


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('CNP', models.CharField(max_length=13, validators=[useful_variables.cnp])),
                ('enrollment', models.CharField(choices=[('Preparatory class', 'Preparatory class'), ('1st grade', '1st grade'), ('2nd grade', '2nd grade'), ('3rd grade', '3rd grade'), ('4th grade', '4th grade'), ('5th grade', '5th grade'), ('6th grade', '6th grade'), ('7th grade', '7th grade'), ('8th grade', '8th grade')], max_length=17)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
